const meyveler = [
    { id: "25",  img: "https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/11919/uploads/urunresimleri/buyuk/granny-smith-elma-kg-1d1e9bd4.png", title: "Elma", price: "12 TL", unit: "kg" },
    { id: "26",  img: "https://ideacdn.net/idea/jw/23/myassets/products/049/mg-8511.jpg?revision=1708687553", title: "Muz", price: "35 TL", unit: "Adet" },
    { id: "27",  img: "https://www.mismarsanalmarket.com/UserFiles/Fotograflar/org/12492-aba4b7b212d42e7c2108a798f99627e3-jpg-aba4b7b212d42e7c2108a798f99627e3.jpg", title: "Portakal", price: "18 TL", unit: "kg" },
    { id: "28",  img: "https://www.medikalakademi.com.tr/wp-content/uploads/2022/05/cilek-strawberry-meyve-6.jpg.webp", title: "Çilek", price: "50 TL", unit: "kg" },
    { id: "29",  img: "https://biosantarim.com/tema/genel/uploads/urunler/kiraz.png", title: "Kiraz", price: "45 TL", unit: "kg" },
    { id: "30",  img: "https://bodurbitki.com/wp-content/uploads/2021/04/armut-santamaria-1c55.jpg", title: "Armut", price: "25 TL", unit: "kg" },
    { id: "31",  img: "https://tropikalturkiye.com/wp-content/uploads/2024/12/greyfurt.png", title: "Greyfurt", price: "28 TL", unit: "kg" },
    { id: "32",  img: "https://www.meyed.org.tr/files/meyed_tarim/bahcecilik/meyveler/seftali/peach.jpg", title: "Şeftali", price: "35 TL", unit: "kg" },
    { id: "33",  img: "https://cdn.cimri.io/market/260x260/nektarin-_224461.jpg", title: "Nektarin", price: "38 TL", unit: "kg" },
    { id: "34", img: "https://biosantarim.com/tema/genel/uploads/urunler/limon.png", title: "Limon", price: "18 TL", unit: "Adet" },
    { id: "35", img: "https://termodizayn.com/thumb.php?p=./img/uploads/muhafazakosullari/icerik/55-karpuz1.jpg&h=434", title: "Karpuz", price: "7 TL", unit: "kg" },
    { id: "36", img: "https://karmentarim.com/uploads/products/thumb/1200x1200//kavun-110.jpg", title: "Kavun", price: "10 TL", unit: "kg" },
    { id: "37", img: "https://ardenmarket.com.tr/media/catalog/product/cache/ce320e98947e5c83f08a8e256dc8423e/a/n/ananas-1.jpg", title: "Ananas", price: "45 TL", unit: "Adet" },
    { id: "38", img: "https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/3140/uploads/urunresimleri/buyuk/f3c1bc1d-8ce6-49e6-b3f8-f19d71cf5c64.jpg", title: "Mango", price: "50 TL", unit: "kg" },
    { id: "39", img: "https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/45567/uploads/urunresimleri/buyuk/1-adet-papaya-meyvesi-cc-385.jpg", title: "Papaya", price: "60 TL", unit: "kg" },
    { id: "40", img: "https://termodizayn.com/webroot/img/uploads/muhafazakosullari/icerik/54-incir.jpg", title: "İncir", price: "25 TL", unit: "kg" },
    { id: "41", img: "https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/36242/uploads/urunresimleri/buyuk/dogal-yaban-mersini-500gr-4107de.jpg", title: "Yaban Mersini", price: "80 TL", unit: "Adet" },
    { id: "42", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxdPAORpQq-33jJKVaguxu_dYpCs2XY4rayA&s", title: "Ahududu", price: "70 TL", unit: "kg" },
    { id: "43", img: "https://www.bizimbahce.net/img/products/frambuaz15_td_1.jpg", title: "Frambuaz", price: "75 TL", unit: "kg" },
    { id: "44", img: "https://bahcemdepeyzaj.com/wp-content/uploads/2022/02/VISNE.jpg", title: "Vişne", price: "45 TL", unit: "kg" },
    { id: "46", img: "https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/45567/uploads/urunresimleri/buyuk/ticimax-frenk-uzumu-redberry-125-gr-f270b5.png", title: "Frenk Üzümü", price: "60 TL", unit: "kg" },
    { id: "47", img: "https://www.emretulumpeyniri.com/img/products/erzincan-yerli-ceviz-4ce3eb9.png", title: "Ceviz", price: "100 TL", unit: "kg" },
    { id: "48", img: "https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/35607/uploads/urunresimleri/buyuk/kestane-kg--ec35-.jpeg", title: "Kestane", price: "40 TL", unit: "kg" },
    { id: "49", img: "https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/11919/uploads/urunresimleri/buyuk/kusburnu-kg-363ee7f1.png", title: "Kuşburnu", price: "50 TL", unit: "kg" },
    { id: "50", img: "https://ideacdn.net/idea/in/11/myassets/products/092/findik-ici-700x700.jpg?revision=1734252148", title: "Fındık", price: "85 TL", unit: "kg" },
    { id: "51", img: "https://www.aydinliamca.com/class/INNOVAEditor/assets/yagli-siyah-zeytin-aydinli-amca-siyah-sele-zeytin-organik-siyah-zeytin-dogal-fermente-zeytin-en-iyi-siyah-zeytin-yagli-zeytin-aydin-zeytin-satisi-aydin-zeytin-fiyatlari-dogal-fermente-siyah-zeytin-aydin-sele-zeytin.jpg", title: "Zeytin", price: "20 TL", unit: "kg" },
    { id: "52", img: "https://ardenmarket.com.tr/media/catalog/product/cache/ce320e98947e5c83f08a8e256dc8423e/n/a/nar_kg.png", title: "Nar", price: "45 TL", unit: "kg" },
    { id: "53", img: "https://static.ticimax.cloud/35637/uploads/urunresimleri/buyuk/kudus-hurma-500-gr-e-6a9d.jpeg", title: "Hurma", price: "90 TL", unit: "kg" },
    { id: "54", img: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Kiwi_%28Actinidia_chinensis%29_1_Luc_Viatour.jpg", title: "Kivi", price: "30 TL", unit: "kg" },
    { id: "55", img: "https://static.ticimax.cloud/8016/uploads/urunresimleri/buyuk/diospyros-kaki-hachiya-trabzon-hurmasi-184-4b.jpg", title: "Cennet Hurması", price: "55 TL", unit: "kg" },
    { id: "56", img: "https://www.almey.com.tr/images/stories/virtuemart/product/z-m-ekirdek-4f511e1b76d86.jpg", title: "Yerli Üzüm", price: "20 TL", unit: "kg" },
    { id: "57", img: "https://images.freeimages.com/images/premium/previews/3824/38243552-dry-fruit-mix.jpg", title: "Meyve Karışımı", price: "90 TL", unit: "kg" },
  ];
  export default meyveler