const SebzeVeMeyve = [
    { id: "1", img: "https://www.mertcantarim.com.tr/wp-content/uploads/2020/01/domates-salkim.jpg", title: "Domates", price: "20 TL", unit: "kg" },
    { id: "54", img: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Kiwi_%28Actinidia_chinensis%29_1_Luc_Viatour.jpg", title: "Kivi", price: "30 TL", unit: "kg" },
    { id: "38", img: "https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/3140/uploads/urunresimleri/buyuk/f3c1bc1d-8ce6-49e6-b3f8-f19d71cf5c64.jpg", title: "Mango", price: "50 TL", unit: "kg" },
    { id: "3", img: "https://static.ticimax.cloud/48857/uploads/urunresimleri/buyuk/-1008937--2684bf.jpg", title: "Patlıcan", price: "25 TL", unit: "kg" },
    { id: "31",  img: "https://tropikalturkiye.com/wp-content/uploads/2024/12/greyfurt.png", title: "Greyfurt", price: "28 TL", unit: "kg" },
    { id: "5", img: "https://ardenmarket.com.tr/media/catalog/product/cache/ce320e98947e5c83f08a8e256dc8423e/k/a/kabak_dolmalik_1.jpg", title: "Kabak", price: "18 TL", unit: "kg" },
    { id: "57", img: "https://images.freeimages.com/images/premium/previews/3824/38243552-dry-fruit-mix.jpg", title: "Meyve Karışımı", price: "90 TL", unit: "kg" },
    { id: "6", img: "https://www.aftamarket.com.tr/sebze-32-sebzeler-manav-12415-17-B.jpg", title: "Soğan", price: "12 TL", unit: "kg" },
    { id: "34", img: "https://biosantarim.com/tema/genel/uploads/urunler/limon.png", title: "Limon", price: "18 TL", unit: "Adet" },
    { id: "7", img: "https://www.mismarsanalmarket.com/UserFiles/Fotograflar/org/3799-2902138-jpg-2902138.jpg", title: "Patates", price: "10 TL", unit: "kg" },
    { id: "55", img: "https://static.ticimax.cloud/8016/uploads/urunresimleri/buyuk/diospyros-kaki-hachiya-trabzon-hurmasi-184-4b.jpg", title: "Cennet Hurması", price: "55 TL", unit: "kg" },
    { id: "8", img: "https://static.ticimax.cloud/11919/uploads/urunresimleri/buyuk/beyaz-lahana-adet-f439.png", title: "Lahana", price: "5 TL", unit: "Adet" },
    { id: "9", img: "https://static.ticimax.cloud/48857/uploads/urunresimleri/buyuk/1009027-f6-451.jpg", title: "Havuç", price: "8 TL", unit: "kg" },
    { id: "10", img: "https://static.ticimax.cloud/48857/uploads/urunresimleri/buyuk/1000205-bda-8f.png", title: "Fasulye", price: "22 TL", unit: "kg" },
    { id: "33",  img: "https://cdn.cimri.io/market/260x260/nektarin-_224461.jpg", title: "Nektarin", price: "38 TL", unit: "kg" },
    { id: "14", img: "https://static.ticimax.cloud/3140/uploads/urunresimleri/buyuk/organik-roka-demet-kurtdogmus-ciftligi-5dfd0a.jpg", title: "Roka", price: "15 TL", unit: "Adet" },
    { id: "46", img: "https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/45567/uploads/urunresimleri/buyuk/ticimax-frenk-uzumu-redberry-125-gr-f270b5.png", title: "Frenk Üzümü", price: "60 TL", unit: "kg" },
    { id: "15", img: "https://static.ticimax.cloud/30547/uploads/urunresimleri/buyuk/ispanak-kg-e88-b1.jpg", title: "Ispanak", price: "12 TL", unit: "Adet" },
    { id: "18", img: "https://static.ticimax.cloud/8320/uploads/urunresimleri/pirasa-kg--40ab-.jpg", title: "Pırasa", price: "18 TL", unit: "kg" },
    { id: "52", img: "https://ardenmarket.com.tr/media/catalog/product/cache/ce320e98947e5c83f08a8e256dc8423e/n/a/nar_kg.png", title: "Nar", price: "45 TL", unit: "kg" },
    { id: "19", img: "https://static.ticimax.cloud/3140/uploads/urunresimleri/buyuk/organik-kereviz-kg--206335.jpg", title: "Kereviz", price: "12 TL", unit: "kg" },
    { id: "20", img: "https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/30523/uploads/urunresimleri/buyuk/taze-bamya-1-kg.-4-ce3337aab635.jpg", title: "Bamya", price: "28 TL", unit: "kg" },
    { id: "41", img: "https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/36242/uploads/urunresimleri/buyuk/dogal-yaban-mersini-500gr-4107de.jpg", title: "Yaban Mersini", price: "80 TL", unit: "Adet" },
    { id: "26",  img: "https://ideacdn.net/idea/jw/23/myassets/products/049/mg-8511.jpg?revision=1708687553", title: "Muz", price: "35 TL", unit: "Adet" },
    { id: "27",  img: "https://www.mismarsanalmarket.com/UserFiles/Fotograflar/org/12492-aba4b7b212d42e7c2108a798f99627e3-jpg-aba4b7b212d42e7c2108a798f99627e3.jpg", title: "Portakal", price: "18 TL", unit: "kg" },
    { id: "47", img: "https://www.emretulumpeyniri.com/img/products/erzincan-yerli-ceviz-4ce3eb9.png", title: "Ceviz", price: "100 TL", unit: "kg" },
    { id: "28",  img: "https://www.medikalakademi.com.tr/wp-content/uploads/2022/05/cilek-strawberry-meyve-6.jpg.webp", title: "Çilek", price: "50 TL", unit: "kg" },
    { id: "29",  img: "https://biosantarim.com/tema/genel/uploads/urunler/kiraz.png", title: "Kiraz", price: "45 TL", unit: "kg" },
    { id: "30",  img: "https://bodurbitki.com/wp-content/uploads/2021/04/armut-santamaria-1c55.jpg", title: "Armut", price: "25 TL", unit: "kg" },
    { id: "13", img: "https://www.ufuktarim.com/imaj/blog/enginar-yetistiriciligi.jpg", title: "Enginar", price: "40 TL", unit: "Adet" },
    { id: "4", img: "https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/48857/uploads/urunresimleri/buyuk/1008997-7276ee.jpg", title: "Biber", price: "30 TL", unit: "kg" },
    { id: "51", img: "https://www.aydinliamca.com/class/INNOVAEditor/assets/yagli-siyah-zeytin-aydinli-amca-siyah-sele-zeytin-organik-siyah-zeytin-dogal-fermente-zeytin-en-iyi-siyah-zeytin-yagli-zeytin-aydin-zeytin-satisi-aydin-zeytin-fiyatlari-dogal-fermente-siyah-zeytin-aydin-sele-zeytin.jpg", title: "Zeytin", price: "20 TL", unit: "kg" },
    { id: "17", img: "https://iis-akakce.akamaized.net/p.z?%2F%2Freimg%2Dcarrefour%2Emncdn%2Ecom%2Fmnresize%2F600%2F600%2Fproductimage%2F30088596%2F30088596%5F0%5FMC%2F8796878045234%5F1528879601057%2Ejpg", title: "Turp", price: "8 TL", unit: "kg" },
    { id: "35", img: "https://termodizayn.com/thumb.php?p=./img/uploads/muhafazakosullari/icerik/55-karpuz1.jpg&h=434", title: "Karpuz", price: "7 TL", unit: "kg" },
    { id: "11", img: "https://reimg-carrefour.mncdn.com/mnresize/600/600/productimage/30017748/30017748_0_MC/8796406546482_1528879452971.jpg", title: "Karnabahar", price: "18 TL", unit: "kg" },
    { id: "36", img: "https://karmentarim.com/uploads/products/thumb/1200x1200//kavun-110.jpg", title: "Kavun", price: "10 TL", unit: "kg" },
    { id: "2", img: "https://www.erenlercep.com/image/cache/catalog/image/catalog/image/catalog/urunler2020/salatalik-kg-550x550.jpg", title: "Salatalık", price: "15 TL", unit: "kg" },
    { id: "37", img: "https://ardenmarket.com.tr/media/catalog/product/cache/ce320e98947e5c83f08a8e256dc8423e/a/n/ananas-1.jpg", title: "Ananas", price: "45 TL", unit: "Adet" },
    { id: "39", img: "https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/45567/uploads/urunresimleri/buyuk/1-adet-papaya-meyvesi-cc-385.jpg", title: "Papaya", price: "60 TL", unit: "kg" },
    { id: "40", img: "https://termodizayn.com/webroot/img/uploads/muhafazakosullari/icerik/54-incir.jpg", title: "İncir", price: "25 TL", unit: "kg" },
    { id: "42", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxdPAORpQq-33jJKVaguxu_dYpCs2XY4rayA&s", title: "Ahududu", price: "70 TL", unit: "kg" },
    { id: "44", img: "https://bahcemdepeyzaj.com/wp-content/uploads/2022/02/VISNE.jpg", title: "Vişne", price: "45 TL", unit: "kg" },
    { id: "12", img: "https://static.ticimax.cloud/3140/uploads/urunresimleri/buyuk/0ce6f65e-10e6-4fb3-80a1-62c3ffbcfe88.jpg", title: "Bezelye", price: "20 TL", unit: "kg" },
    { id: "48", img: "https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/35607/uploads/urunresimleri/buyuk/kestane-kg--ec35-.jpeg", title: "Kestane", price: "40 TL", unit: "kg" },
    { id: "49", img: "https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/11919/uploads/urunresimleri/buyuk/kusburnu-kg-363ee7f1.png", title: "Kuşburnu", price: "50 TL", unit: "kg" },
    { id: "50", img: "https://ideacdn.net/idea/in/11/myassets/products/092/findik-ici-700x700.jpg?revision=1734252148", title: "Fındık", price: "85 TL", unit: "kg" },
    { id: "43", img: "https://www.bizimbahce.net/img/products/frambuaz15_td_1.jpg", title: "Frambuaz", price: "75 TL", unit: "kg" },
    { id: "32",  img: "https://www.meyed.org.tr/files/meyed_tarim/bahcecilik/meyveler/seftali/peach.jpg", title: "Şeftali", price: "35 TL", unit: "kg" },
    { id: "53", img: "https://static.ticimax.cloud/35637/uploads/urunresimleri/buyuk/kudus-hurma-500-gr-e-6a9d.jpeg", title: "Hurma", price: "90 TL", unit: "kg" },
    { id: "25",  img: "https://static.ticimax.cloud/cdn-cgi/image/width=-,quality=85/11919/uploads/urunresimleri/buyuk/granny-smith-elma-kg-1d1e9bd4.png", title: "Elma", price: "12 TL", unit: "kg" },
    { id: "16", img: "https://gurmar.com.tr/images/thumbs/0005606_marul-adet_510.jpg", title: "Marul", price: "5 TL", unit: "Adet" },
    { id: "56", img: "https://www.almey.com.tr/images/stories/virtuemart/product/z-m-ekirdek-4f511e1b76d86.jpg", title: "Yerli Üzüm", price: "20 TL", unit: "kg" },
];
export default SebzeVeMeyve